### ISSUE TITLE
Bug in WoodyConstants?

### ISSUE THREAD

**Issue by IceReaper** [scemino/NScumm.Audio#16]
This looks like a bug to me. due to int division, the resulting double will always be 0.

https://github.com/scemino/NScumm.Audio/blob/e28d26fc0048b530b1eb685cc2853ad748316222/NScumm.Audio/OPL/Woody/WoodyConstants.cs#L67

**Comment by scemino** [comment]
> This looks like a bug to me. due to int division, the resulting double will always be 0.
> 
> https://github.com/scemino/NScumm.Audio/blob/e28d26fc0048b530b1eb685cc2853ad748316222/NScumm.Audio/OPL/Woody/WoodyConstants.cs#L67

Yes, you're right, in the original source it was used as a macro, this is a bad translation.
