### ISSUE TITLE
DRO file can't be played

### ISSUE THREAD

**Issue by ghost** [scemino/NScumm.Audio#2]
When trying to play a DRO file captured using latest DOSBox version which plays correctly in Audacious/Foobar2000 (using adplug), I get this message:

This music file is not supported

Attached is a sample DRO file which does not play.

[test.zip](https://github.com/scemino/NScumm.Audio/files/4939401/test.zip)

**Comment by scemino** [comment]
It is a DRO V2 file, fixed in commit 7b1866e3117b9ffe1986209db0813ca1c8e8c51b
