### ISSUE TITLE
Render audio without relying on system clock

### ISSUE THREAD

**Issue by BenMcLean** [scemino/NScumm.Audio#3]
I'd like to be able to use this to convert [IMF songs](https://en.wikipedia.org/wiki/IMF_(file_format)) to streaming audio using the same or similar method to what [IMF2WAV](http://k1n9duk3.shikadi.net/imftools.html) does.

The problem is that the API provided by NScumm.Audio is limited to sending notes to the (emulated) hardware in real time. Source code is included with IMF2WAV and if you look at what its `fmopl.h` does, it provides a much bigger API than `IOpl.cs` to allow managing time any way the user wants rather than being restricted to real time only. Could NScumm.Audio be changed to provide similar functions?

**Comment by scemino** [comment]
I totally agree, it should be doable.

**Comment by BenMcLean** [comment]
I was totally wrong when I wrote this. The API does not use the system clock.

What happens instead is that time in the simulation moves forward a little for each frame of audio when it is output to the frame buffer. `ReadBuffer` is what moves time forward and it is completely agnostic about whether that's happening in real time or not.
