### ISSUE TITLE
NScumm.Audio.Players should accept byte streams, not files

### ISSUE THREAD

**Issue by BenMcLean** [scemino/NScumm.Audio#5]
File management should be done completely outside of NScumm.Audio.Players. It should not expect to have access to the file system. Instead of expecting a file, its API should expect a byte stream. It should be up to the user to decide (in their outside code) whether that byte stream comes from a file or a byte array in RAM or a web api or anything else it could be. This becomes particularly important on mobile devices or web apps which may not have permission to use the file system. Loading from a file system path could be provided as an option by a wrapper method to create the stream but should not be required.

I'll be putting together a PR that does this for ImfPlayer at least.

**Comment by BenMcLean** [comment]
Also, why on God's green earth are these classes internal and sealed instead of public? All the players should be public.

**Comment by scemino** [comment]
I'm OK with that also.
